@echo off
echo [?? Antigravity Safe Update] Memulai proses update aman...
echo 1. Menarik versi terbaru Open WebUI...
docker-compose pull
echo 2. Menjalankan container baru...
docker-compose up -d
echo 3. Menyuntikkan kembali fitur super hebat Antigravity...
docker exec open-webui python /app/antigravity_master_patcher.py
echo 4. Restarting container untuk aktivasi fitur...
docker restart open-webui
echo [? SELESAI] Antigravity IDE telah diperbarui ke versi terbaru!
pause
